version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "14:00"
    open-pull-requests-limit: 3
    reviewers:
      - "nydiokar"
    assignees:
      - "nydiokar"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    groups:
      security-updates:
        applies-to: security-updates
        update-types:
          - "patch"
      major-updates:
        update-types:
          - "major"
      key-security-libs:
        patterns:
          - "pykeepass"
          - "cryptography"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    reviewers:
      - "nydiokar"
    assignees:
      - "nydiokar"
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
